export const FETCH_CRYPTO = 'FETCH_CRYPTO'
export const FETCH_FIAT = 'FETCH_FIAT'

export const FETCH_START = 'FETCH_START'
export const FETCH_FAIL = 'FETCH_FAIL'
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS'
export const FETCH_FIAT_SUCCESS = 'FETCH_FIAT_SUCCESS'

export const CALCULATE = 'CALCULATE'
export const CALCULATE_SUCCESS = 'CALCULATE_SUCCESS'
export const CALCULATE_CLEAR = 'CALCULATE_CLEAR'

export const VALIDATE_SET = 'VALIDATE_SET'