export const FETCH_CRYPTO = 'FETCH_CRYPTO'
export const FETCH_FIAT = 'FETCH_FIAT'

export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_CRYPTO_SUCCESS = 'FETCH_CRYPTO_SUCCESS'
export const FETCH_FIAT_SUCCESS = 'FETCH_FIAT_SUCCESS'
export const FETCH_FAIL = 'FETCH_FAIL'
